name: Contracts

on:
  pull_request:
    branches: [master]
    paths: [contracts/**]

  push:
    branches: [master]
    paths: [contracts/**]

jobs:
  contracts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: cargo build --release --workspace --manifest-path contracts/Cargo.toml

    - name: Test
      run: cargo test --release --workspace --manifest-path contracts/Cargo.toml
